apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
spec:
  replicas: "two"
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        securityContext:
          privileged: true
