name: K8s Manifest Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Kubeconform (The Grammar Check)
      # We use the -strict flag just like you did in your terminal
      - name: Run Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: "-summary -strict -verbose -output pretty ."

      # 2. Trivy (The Security Check)
      # This will fail the build if it finds HIGH or CRITICAL vulnerabilities
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: true
          exit-code: '1' # This tells GH Actions to fail the job if issues are found
          severity: 'HIGH,CRITICAL'
          scan-ref: '.'

      # 3. Optional: Kube-score (The Quality Check)
      - name: Run Kube-score
        run: |
          docker run --rm -v $(pwd):/project zegl/kube-score:latest score /project/*.yaml
